// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDndH76kAM-R1f0mxrXetreu4ZV7-RfJdA',
    appId: '1:406719016032:web:2894e5fd32d9e65fd52705',
    messagingSenderId: '406719016032',
    projectId: 'bodyfit-83f2c',
    authDomain: 'bodyfit-83f2c.firebaseapp.com',
    storageBucket: 'bodyfit-83f2c.firebasestorage.app',
    measurementId: 'G-FTZYKYWHHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Imyc55WHxSs1faOgnUzBvTuSMRRoopk',
    appId: '1:406719016032:android:f67e80a172227671d52705',
    messagingSenderId: '406719016032',
    projectId: 'bodyfit-83f2c',
    storageBucket: 'bodyfit-83f2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlOLqJ7GMTZTIw55hwiJnw1Y_1HTXRpRU',
    appId: '1:406719016032:ios:58b0fbcc718ac162d52705',
    messagingSenderId: '406719016032',
    projectId: 'bodyfit-83f2c',
    storageBucket: 'bodyfit-83f2c.firebasestorage.app',
    iosBundleId: 'com.example.bodyfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlOLqJ7GMTZTIw55hwiJnw1Y_1HTXRpRU',
    appId: '1:406719016032:ios:58b0fbcc718ac162d52705',
    messagingSenderId: '406719016032',
    projectId: 'bodyfit-83f2c',
    storageBucket: 'bodyfit-83f2c.firebasestorage.app',
    iosBundleId: 'com.example.bodyfit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDndH76kAM-R1f0mxrXetreu4ZV7-RfJdA',
    appId: '1:406719016032:web:a39b005469ea05c6d52705',
    messagingSenderId: '406719016032',
    projectId: 'bodyfit-83f2c',
    authDomain: 'bodyfit-83f2c.firebaseapp.com',
    storageBucket: 'bodyfit-83f2c.firebasestorage.app',
    measurementId: 'G-CQJJ1CBTBR',
  );
}
